# 3/14 수업
# 변수정의

In [25]:
a = 1; print(type(a))

<class 'int'>


#### a=1이기 때문에 a의 class를 int(정수)라고 출력한다.

In [26]:
a = 1; a = float(a); print(type(a))
a

<class 'float'>


1.0

#### int인 a를 float로 변환시킨다. 

In [27]:
a = 1.2; a = int(a); print(type(a))
a

<class 'int'>


1

#### a는 float지만 int로 변환시킨다.

In [28]:
a = '123'; print(type(a)); print(a[1])
print(a[-1])

<class 'str'>
2
3


#### '' 안에 문자나 숫자를 써서 a를 string으로 정의하고 [ ]안에 index를 입력하면 해당 순서의 문자나 숫자가 출력된다.
#### 첫 번째에 해당하는 index는 0이고 그 뒤로 1,2,3,4, 순이다. -1의 index는 맨 오른쪽에서 첫 번째라는 뜻으로 맨 뒤의 요소를 의미한다. 뒤에서 앞으로 오면서 index는 -1,-2,-3, 순의 값을 갖는다.

In [29]:
a= '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


#### str a를 list로 변형시키면 각 문자들이 쪼개져서 문자형태로 list를 이룬다.

In [30]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])
print(a[-1][1])

<class 'list'>
1
2
[3, '4']
4


#### 숫자와 문자, 또다른 list를 모두 하나의 큰 list로 정의할 수 있다. 
#### [ ]를 두 번 사용하면 큰 list 안에 속한 list의 요소를 불러올 수 있다.

In [31]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


#### list의 [ ]를 ( )로 바꾸면 tuple이 된다. 리스트와 비슷하다고 보면 된다.

In [32]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


#### list의 [ ]를 { }로 바꾸고 :를 이용하여 앞에 key, 뒤에 value를 pairwise하면 dictionary가 된다. 각각의 문자에는 모두 ''기호를 써야한다.
#### [ ]에 key값을 입력하면 해당 value가 출력된다.

In [33]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

#### tuple은 ( )를 사용하고 list와 비슷하다. tuple과 list를 이용하여 행렬과 비슷한 형태를 이룰 수 있다.
  * ,를 기준으로 두 개의 tuple이 세로로 정렬되어 2by3의 행렬과 비슷한 모양을 이룬다.

In [34]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


#### import는 파이썬 자체 내에 있지 않는 함수 패키지를 가져올 때 사용하며 여기서는 numpy라는 함수를 np로 받는다.
#### np.array를 입력하여 numpy패키지 속의 array함수를 사용한다. 꼭 array함수의 위치를 np.로 명시해야한다.
#### array함수는 tuple이 들어있는 list를 matrix의 형태로 정렬하는 함수다. 
* 이 값을 받은 b의 class는 numpy.ndarray로 numpy가 제공하는 array를 사용한 단위라는 의미다.

In [35]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


#### 그러나 array는 행렬을 만들어주는 함수는 아니므로 b*b를 실행하면 같은 위치에 있는 element by element로 곱해진 값을 출력한다.

In [36]:
c = np.matrix(b)
print(c)
print(type(c))
c*c

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#### numpy에 정의되어있는 matrix함수는 형태 뿐만 아니라 성질까지 행렬로 변형시키는 함수이다. 따라서 c*c를 할 경우 에러가 발생한다.

In [37]:
c*c.T

matrix([[14, 19],
        [19, 73]])

#### T라는 행렬의 행과 열을 맞바꿔주는 transpose함수를 이용하여 2by3의 행렬c를 3by2의 행렬로 변환하고 곱하면 정상적으로 2by2의 행렬값이 계산된다. T를 사용할 때 .T의 형식으로 사용해야한다.